import fs from 'fs';
import path from 'path';

const IMAGE_EXT = ['.jpeg', '.jpg', '.png'];
const VIDEO_EXT = ['.mp4', '.mov', '.webm', '.ogg'];

function scanFolder(folderPath: string) {
  if (!fs.existsSync(folderPath)) {
    return { images: [], videos: [] };
  }
  const files = fs.readdirSync(folderPath);
  const images = files
    .filter(f => IMAGE_EXT.some(ext => f.toLowerCase().endsWith(ext)))
    .sort();
  const videos = files
    .filter(f => VIDEO_EXT.some(ext => f.toLowerCase().endsWith(ext)))
    .sort();
  return { images, videos };
}

const day1Path = path.join(process.cwd(), 'public/qbr/day1');
const day2Path = path.join(process.cwd(), 'public/qbr/day2');
const day3Path = path.join(process.cwd(), 'public/qbr/day3');

const day1 = scanFolder(day1Path);
const day2 = scanFolder(day2Path);
const day3 = scanFolder(day3Path);

const content = `/**
 * Auto-generated by scripts/populate-gallery.ts
 * Do not edit manually - run "pnpm run populate-gallery" to update
 */
export const day1ImageFiles: string[] = ${JSON.stringify(day1.images, null, 2)};
export const day1VideoFiles: string[] = ${JSON.stringify(day1.videos, null, 2)};
export const day2ImageFiles: string[] = ${JSON.stringify(day2.images, null, 2)};
export const day2VideoFiles: string[] = ${JSON.stringify(day2.videos, null, 2)};
export const day3ImageFiles: string[] = ${JSON.stringify(day3.images, null, 2)};
export const day3VideoFiles: string[] = ${JSON.stringify(day3.videos, null, 2)};
`;

const outputPath = path.join(process.cwd(), 'src/data/gallery.ts');
fs.writeFileSync(outputPath, content, 'utf-8');

console.log(`✅ Populated gallery.ts:`);
console.log(`   Day 1: ${day1.images.length} images, ${day1.videos.length} videos`);
console.log(`   Day 2: ${day2.images.length} images, ${day2.videos.length} videos`);
console.log(`   Day 3: ${day3.images.length} images, ${day3.videos.length} videos`);
