/**
 * Auto-generated by scripts/populate-gallery.ts
 * Do not edit manually - run "pnpm run populate-gallery" to update
 */
export const day1ImageFiles: string[] = [
  "WhatsApp Image 2026-02-16 at 14.21.09.jpeg",
  "WhatsApp Image 2026-02-16 at 14.21.11 (1).jpeg",
  "WhatsApp Image 2026-02-16 at 14.21.11.jpeg",
  "WhatsApp Image 2026-02-16 at 14.21.12 (1).jpeg",
  "WhatsApp Image 2026-02-16 at 14.21.12.jpeg",
  "WhatsApp Image 2026-02-16 at 14.21.25 (1).jpeg",
  "WhatsApp Image 2026-02-16 at 14.21.25.jpeg"
];
export const day1VideoFiles: string[] = [
  "WhatsApp Video 2026-02-16 at 14.21.12.mp4",
  "WhatsApp Video 2026-02-16 at 14.21.24.mp4"
];
export const day2ImageFiles: string[] = [
  "WhatsApp Image 2026-02-16 at 14.26.07 (1).jpeg",
  "WhatsApp Image 2026-02-16 at 14.26.07 (2).jpeg",
  "WhatsApp Image 2026-02-16 at 14.26.07.jpeg"
];
export const day2VideoFiles: string[] = [
  "WhatsApp Video 2026-02-16 at 14.26.07.mp4"
];
export const day3ImageFiles: string[] = [
  "WhatsApp Image 2026-02-16 at 14.54.17.jpeg",
  "WhatsApp Image 2026-02-16 at 14.54.18.jpeg",
  "WhatsApp Image 2026-02-16 at 14.54.21.jpeg",
  "WhatsApp Image 2026-02-16 at 14.54.24.jpeg",
  "WhatsApp Image 2026-02-16 at 15.03.34 (1).jpeg",
  "WhatsApp Image 2026-02-16 at 15.03.34.jpeg",
  "WhatsApp Image 2026-02-16 at 15.03.35 (1).jpeg",
  "WhatsApp Image 2026-02-16 at 15.03.35 (2).jpeg",
  "WhatsApp Image 2026-02-16 at 15.03.35 (3).jpeg",
  "WhatsApp Image 2026-02-16 at 15.03.35.jpeg"
];
export const day3VideoFiles: string[] = [];
